INSERT INTO job_listings
  (title, company, company_website, salary, location, job_type, description, tags, apply_url, is_bootstrapped, date_posted)
VALUES
(
  'Growth Marketing Manager',
  'Payhip',
  'https://payhip.com',
  '$75,000 – $99,000',
  'Remote · Worldwide',
  'Full-time',
  'Payhip is a profitable, bootstrapped startup powering 150,000+ entrepreneurs to sell digital products online. Looking for a growth marketer to identify high-impact opportunities and drive organic and paid acquisition.',
  ARRAY['Marketing', 'SEO', 'PPC'],
  'https://weworkremotely.com/remote-jobs/payhip-growth-marketing-manager',
  true,
  '2026-07-01'
),
(
  'Head of Product',
  'Gruntwork',
  'https://gruntwork.io',
  '$150,000 – $180,000',
  'Remote · Worldwide',
  'Full-time',
  'Gruntwork is a profitable, bootstrapped DevOps company with no outside investors. Globally recognized for open source tools like Terragrunt used by thousands of companies from startups to Fortune 500s.',
  ARRAY['Product', 'DevOps', 'SaaS'],
  'https://jobs.ashbyhq.com/gruntwork/c216e88e-2580-447d-9ea7-665ef00b15ea',
  true,
  '2026-07-01'
),
(
  'Customer Onboarding & Support Specialist',
  'Gymflow',
  'https://gymflow.io',
  '$45,000 – $65,000',
  'Remote · South Africa',
  'Full-time',
  'Gymflow is a founder-led, bootstrapped SaaS platform for gym and fitness studio owners. Small, focused team of 11 where your impact is immediate and visible.',
  ARRAY['Customer Success', 'SaaS', 'Onboarding'],
  'https://weworkremotely.com/remote-jobs/gymflow-customer-onboarding-support-specialist-remote-south-africa',
  true,
  '2026-07-01'
),
(
  'Senior Software Engineer',
  'Aha!',
  'https://www.aha.io',
  '$130,000 – $160,000',
  'Remote · Worldwide',
  'Full-time',
  'Aha! is a self-funded, profitable, 100% remote product development company used by 700,000+ builders worldwide. They champion the Bootstrap Movement and have never taken outside funding.',
  ARRAY['Engineering', 'Ruby', 'SaaS'],
  'https://www.aha.io/company/careers/current-openings',
  true,
  '2026-07-01'
),
(
  'Technical Customer Success Manager',
  'Plausible Analytics',
  'https://plausible.io',
  'Negotiable',
  'Remote · Worldwide',
  'Full-time',
  'Plausible Analytics is a privacy-first, open-source Google Analytics alternative. Fully bootstrapped and profitable with a small remote team. Looking for a technical customer success manager to help customers get the most out of the product.',
  ARRAY['Customer Success', 'Analytics', 'SaaS'],
  'https://plausible.io/jobs/customer-success',
  true,
  '2026-07-05'
),
(
  'Founding Customer Success Manager',
  'Wrenly',
  'https://wrenly.ai',
  '$16,000 – $26,000 + commission',
  'Remote · Brazil',
  'Full-time',
  'Wrenly is a bootstrapped, profitable HR and people-analytics SaaS. First CSM hire — you will own onboarding, support, QBRs, renewals and expansion. Requires Brazil timezone and 100+ hours of real hands-on AI agent experience.',
  ARRAY['Customer Success', 'HR Tech', 'AI', 'SaaS'],
  'https://wrenly.ai',
  true,
  '2026-07-05'
),
(
  'Full-Stack Engineer',
  'Relevant Healthcare',
  'https://relevant.healthcare',
  'Competitive',
  'Remote · Worldwide',
  'Full-time',
  'Relevant builds a data platform that helps safety-net healthcare providers deliver better care. Bootstrapped, no external capital whatsoever, and profitable. Small team of ~25, modern stack (Rails, TypeScript, React, GraphQL, d3), healthy approach to tech debt and work/life balance.',
  ARRAY['Engineering', 'Ruby on Rails', 'TypeScript', 'React', 'GraphQL', 'Healthcare'],
  'https://relevant.healthcare/jobs',
  true,
  '2026-07-05'
),
(
  'Full-Stack Product Engineer',
  'Featurebase',
  'https://featurebase.app',
  'Competitive',
  'Remote · Worldwide',
  'Full-time',
  'Featurebase is a fully bootstrapped, profitable customer support and product feedback platform powering thousands of teams including Lovable, Raycast, and n8n. Small team, high autonomy, ship meaningful work. Stack: Next.js + TypeScript, Node.js, MongoDB, Redis.',
  ARRAY['Engineering', 'Next.js', 'TypeScript', 'Node.js', 'MongoDB', 'SaaS'],
  'https://go.featurebase.app/careers',
  true,
  '2026-07-05'
),
(
  'Senior Full-Stack Engineer',
  'CO-Ver',
  'https://co-ver.com',
  '$150,000 – $175,000',
  'Remote · US only',
  'Full-time',
  'CO-Ver is a self-funded, intentionally small SaaS company. Looking for a senior full-stack engineer to join a lean, high-impact team. Strong salary for the right candidate who values autonomy and working without bureaucracy.',
  ARRAY['Engineering', 'SaaS', 'Fullstack'],
  'mailto:recruiting@co-ver.com',
  true,
  '2026-07-05'
),
(
  'Multiple Engineering & Specialist Roles',
  'SerpApi',
  'https://serpapi.com',
  '$150,000 – $180,000',
  'Remote · Worldwide',
  'Full-time',
  'SerpApi is the leading API to scrape and parse search engine results, providing 100+ APIs for Google, Bing, Baidu, and more. Hiring across multiple roles including Engineers, Customer Success, Developer Advocates, and SEO Specialists. Profitable, founder-led, remote-first.',
  ARRAY['Engineering', 'Python', 'Ruby', 'JavaScript', 'Developer Advocate', 'SEO'],
  'https://serpapi.com/careers',
  true,
  '2026-07-05'
),
(
  'Multiple Roles',
  'Close CRM',
  'https://close.com',
  '$75,000 – $155,000',
  'Remote · Worldwide',
  'Full-time',
  'Close builds a CRM that helps sales teams spend more time selling and less time on data entry. Bootstrapped and profitable since 2013 with ~110 employees working asynchronously across the globe. Known for 4-week paid sabbatical every 5 years.',
  ARRAY['Sales', 'Customer Success', 'Marketing', 'SaaS', 'CRM'],
  'https://close.com/careers',
  true,
  '2026-07-05'
);
